This is makeindex, version 2.15 [TeX Live 2022/dev] (kpathsea + Thai support).
Scanning style file ./main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file main.acn...
!! Input index error (file = main.acn, line = 1):
   -- Illegal page number .
!! Input index error (file = main.acn, line = 2):
   -- Illegal page number .
.done (45 entries accepted, 2 rejected).
Sorting entries....done (281 comparisons).
Generating output file main.acr....done (57 lines written, 0 warnings).
Output written in main.acr.
Transcript written in main.alg.
