all_robot_names:
- Aramis
- Athos
- Porthos
#- Dartagnan
- Edmon
#- Mercedes
robot_neighbors:
  Aramis:
  #- Athos
  - Porthos
  #- Dartagnan
  - Edmon
  Athos:
  - Porthos
  #- Aramis
  #- Dartagnan
  - Edmon
  #Dartagnan:
  #- Athos
  #- Aramis
  #- Porthos
  Edmon:
  - Aramis
  - Athos
  #- Porthos
  Porthos:
  - Athos
  - Aramis
  #- Dartagnan
  #- Edmon
