all_robot_names:
#- Aramis
#- Athos
- Porthos
- Edmon
- Dartagnan
- Mercedes
robot_neighbors:
  #Aramis:
  #- Athos
  #- Porthos
  #- Dartagnan
  #- Edmon
  #Athos:
  #- Porthos
  #- Aramis
  #- Dartagnan
  #- Edmon
  Dartagnan:
  #- Athos
  #- Aramis
  #- Porthos
  - Mercedes
  - Edmon
  Mercedes:
  #- Athos
  #- Aramis
  #- Porthos
  - Dartagnan
  - Porthos
  Edmon:
  #- Aramis
  #- Athos
  - Porthos
  - Dartagnan
  Porthos:
  #- Athos
  #- Aramis
  #- Dartagnan
  - Edmon
  - Mercedes