all_robot_names:
- Aramis
- Athos
#- Dartagnan
#- Edmon
- Porthos
robot_neighbors:
  Aramis:
  #- Edmon
  #- Dartagnan
  - Porthos
  - Athos
  Athos:
  #- Dartagnan
  #- Edmon
  - Porthos
  - Aramis
  #Dartagnan:
  #- Athos
  #- Aramis
  #- Porthos
  #Edmon:
  #- Aramis
  #- Athos
  #- Porthos
  Porthos:
  - Aramis
  - Athos
  #- Dartagnan
  #- Edmon
