all_robot_names:
- Aramis
- Athos
- Porthos
- Dartagnan
- Edmon
robot_neighbors:
  Aramis:
  - Porthos
  - Edmon
  Athos:
  - Dartagnan
  - Edmon
  Dartagnan:
  - Athos
  - Edmon
  Edmon:
  - Dartagnan
  - Aramis
  - Athos
  - Porthos
  Porthos:
  - Aramis
  - Edmon
